spring:
  redis:
    host: 192.168.24.93
    port: 6379
    password: Garen666
    timeout: 5000ms
  session:
    store-type: redis
    timeout: 3600s
    redis:
      flush-mode: on_save
      namespace: spring:session